# Generated by Django 2.1.7 on 2019-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cate',
            name='cate_img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='cate',
            name='cate_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ureg',
            name='utype',
            field=models.CharField(default='costumer', max_length=10),
        ),
    ]
