# Generated by Django 2.1.7 on 2019-03-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bcomm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcomm',
            name='bumail',
        ),
    ]
