# Generated by Django 2.2.3 on 2020-11-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190316_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ureg',
            old_name='uaddr',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='ureg',
            old_name='ucard',
            new_name='cardNumber',
        ),
        migrations.RenameField(
            model_name='ureg',
            old_name='uphone',
            new_name='confirmPassword',
        ),
        migrations.RenameField(
            model_name='ureg',
            old_name='umail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ureg',
            old_name='ufname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='ureg',
            old_name='uname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='ureg',
            old_name='upass',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='ureg',
            old_name='utype',
            new_name='userType',
        ),
        migrations.RenameField(
            model_name='ureg',
            old_name='usname',
            new_name='username',
        ),
    ]
