# Generated by Django 2.2.3 on 2020-11-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20201125_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='ureg',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
    ]
