# Generated by Django 2.1.7 on 2019-03-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190315_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bcomm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=100)),
                ('bumail', models.EmailField(max_length=254)),
                ('bcom', models.TextField()),
            ],
        ),
    ]
