# Generated by Django 2.1.7 on 2019-03-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_bcomm_bumail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbid', models.IntegerField()),
                ('cbtitle', models.CharField(max_length=100)),
                ('cbmail', models.EmailField(max_length=254)),
                ('cstat', models.CharField(default='no', max_length=3)),
                ('cdeli', models.CharField(default='no', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='bcomm',
            name='bumail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
